name:                course-work
version:             0.1.0.0
github:              "githubuser/course-work"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/course-work#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

internal-libraries:
  course-work-lib:
    source-dirs: src/course-work-lib
    dependencies:
    - parsec
    - containers
  testing-utils:
    source-dirs: src/testing-utils
    dependencies:
    - course-work-lib
    - parsec
    - containers
    - test-framework
    - test-framework-hunit
    - HUnit

executables:
  course-work-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - course-work-lib
    - containers
    
data-files:
- test/data/*.txt

tests:
  parser-test:
    main:		 Main.hs
    source-dirs:	 test/ParserTest
    dependencies:
    - course-work-lib
    - testing-utils
    - HUnit
    - test-framework
    - test-framework-hunit
    - containers
    generated-other-modules:
    - Paths_course_work
  kripke-model-test:
    main:                Main.hs
    source-dirs:	 test/KripkeModelTest
    dependencies:
    - course-work-lib
    - testing-utils
    - HUnit
    - test-framework
    - test-framework-hunit
    - containers
    generated-other-modules:
    - Paths_course_work
  formula-test:
    main:                Main.hs
    source-dirs:	 test/FormulaTest
    dependencies:
    - course-work-lib
    - testing-utils
    - HUnit
    - test-framework
    - test-framework-hunit
    - containers
    generated-other-modules:
    - Paths_course_work
  


